{% set version = "7.4.4" %}

package:
  name: grass
  version: {{ version }}

source:
  - url: https://grass.osgeo.org/grass74/source/grass-{{ version }}.tar.gz
    sha256: 96a39e273103f7375a670eba94fa3e5dad2819c5c5664c9aee8f145882a94e8c
    patches:
      - 0001-platform.make.in.patch  # [osx]
      - 0002-platform.make.in-linux.patch  # [linux]
      - 0003-loader.py.patch  # [osx]
      - 0004-rules.make.patch  # [osx]
      - 0005-rules.make-linux.patch  # [linux]
      - 0006-aclocal.m4.patch  # [osx]
      - 0007-configure.patch  # [osx]
      - 0008-install.make.patch  # [osx]
      - 0009-module.make.patch  # [osx]
      - 0010-shlib.make.patch  # [osx]
      - 0011-win-package-mklibs.patch  # [win]
      - 0012-win-fix-cairo-no-fontconfig.patch  # [win]
      - 0013-win-fix-gpde-make.patch  # [win]
      - 0014-add-python2-pkg-support.patch  # [win]

build:
  number: 1002
  # Let's not compile Py2.7 src with Py3.x
  skip_compile_pyc:
    - "*/*.py"

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('cxx') }}  # [unix]
    # Win build currently uses C:\msys64 standard/portable install
    # - {{ compiler('m2w64_c') }}  # [win]
    # - {{ compiler('m2w64_cxx') }}  # [win]
    - pkg-config  # [unix]
    - m4  # [unix]
    - bison  # [unix]
    - flex  # [unix]
    - m2-patch  # [win]
  host:
    - libgdal
    - proj4
    - geos
    - sqlite
    - jpeg
    - libpng
    - giflib
    - libtiff
    - libiconv
    - fftw
    - freetype
    - cairo
    - openblas
    - krb5
    - pandoc
    {% if not win %}
    - python <3
    - python.app  # [osx]
    - wxpython
    - numpy
    - pillow
    {% else %}
    # Python2 not needed in conda env, if building in msys2 env
    - libpq
    - liblas 1.8.*
    # libxdr is static
    - libxdr
    - pdcurses
    # - gnu-regex
    {% endif %}
  run:
    # These are needed on Win for their Library/share data
    - libgdal
    - proj4
    - geos
    - sqlite
    - jpeg
    - libpng
    - giflib
    - libtiff
    - libiconv
    - fftw
    - freetype
    - cairo
    - openblas
    - krb5
    # - pandoc
    {% if not win %}
    - python <3
    - python.app  # [osx]
    - gdal
    - wxpython
    - matplotlib
    - numpy
    - pillow
    {% else %}
    - libpq
    - liblas 1.8.*
    - pdcurses
    {% endif %}
    - grass-python2

test:
  requires:
    # this ensures there is a `python2` available on PATH
    - python2
  commands:
    - grass74 --help
    - grass74 --version
    - grass74 --config
    - if not exist "%LIBRARY_BIN%\\grass_env.bat" exit 1  # [win]

about:
  home: https://grasswiki.osgeo.org/
  license: GPL-2.0
  license_family: GPL
  license_file: lib/init/license.txt
  summary: Geographic Resources Analysis Support System
  description: |
    GRASS GIS, commonly referred to as GRASS (Geographic Resources
    Analysis Support System), is a free and open source Geographic
    Information System (GIS) software suite used for geospatial data
    management and analysis, image processing, graphics and maps
    production, spatial modeling, and visualization.
  dev_url: https://grass.osgeo.org/development/
  doc_url: https://grasswiki.osgeo.org/

extra:
  recipe-maintainers:
    - mcflugen
    - dakcarto
